# Generated by Django 4.1.7 on 2023-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_recieved', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='salesmanager.product')),
            ],
        ),
    ]
