# Generated by Django 4.1.7 on 2023-04-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
