# Generated by Django 4.1.7 on 2023-04-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesmanager.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesmanager.product')),
            ],
        ),
    ]
