# Generated by Django 4.1.7 on 2023-04-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0008_appointment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
